
entity = ['Trade_Name',
        'Effective_Date',
        'Tenant_Name',
        'Landlord_Name',
        'Premises_Address',
        'Area_of_Premises',
        'Commencement_Date',
        'Expiration_Date',
        'Tenant_Notice_Address',
        'Tenant_Notice_Copy_To_Address',
        'Billing_Address',
        'Base_Rent',
        'Additional_Rent',
        'Renewal_Option',
        'Expansion_Option',
        'Termination_Right',
        'RIGHT_OF_FIRST_OFFER',
        'Default_Clause',
        'Late_Charges',
        'Holdover_Rent',
        'Contraction_Option',
        'Tenants_Insurance_Clause',
        'Assignment_Clause',
        'Co_tenancy_Clause',
        'Common_Area_Expenses',
        'Landlord_Notice_Address',
        'Guarantor',
        'Surrender',
        'Security_Deposit',
        'Parking_Space',
        'Utilities',
        'Permitted_Use',
        'Radius_Restriction',
        'Sales_KirckOut',
        'Signage_Clause',
        'Estoppel_Certificate',
        'Subordination_SNDA',
        'Tenant_Improvement_Allowance',
        'Relocation',
        'Tenants_Maintenance',
        'Landlord_Maintenance',
        'Alterations',
        'Satellite_Dish',
        'Flex_Furniture',
        'Fitness_Center',
        'Conference_Center'
         ]




queries = ["What is the Trade Name or DBA or Do Business As Name in this agreement?",
        "What is the Lease Date or the Effective Date of this agreement?",
        "What is the Tenanat Name or lease details or summary in this Lease Agreement?",
        "What is the Landlord's Name or lease details or summary in this Lease Agreement?",
        "What is the Premises Address mentioned in this agreement?",
        "What is the Area of Premises mentioned this agreement?Give the answer in Square Feet.",
        "What is the Commencement Date of this agreement or lease details or summary in this Lease Agreement?",
        "What is the Expiration Date or the Termination Date of this agreement?",
        "What is the Tenant Notice Address mentioned in this agreement?",
        "What is the Tenant Notice Copy To Address mentioned in this agreement?",
        "What is the Billing Address mentioned in this agreement?",
        "Extract and calculate the Base Rent terms provided in the lease document, including the Start Date, End Date, Monthly Rent, Annual Rent, and Rent per Square Foot (PSF) for each period.",
        "Extract and calculate the Additional Rent terms which are other than Base Rent from the lease document, including the Start Date, End Date, Monthly Rent, Annual Rent, and Rent per Square Foot (PSF) for each period.",
        "What is the Renewal Option mentioned in this agreement?Extract the terms related to the Renewal Option provided in the lease document, including Renewal notice period,Renewal term, rental rate, annual rent increases, and conditions for exercising the option",
        "What is the Expansion Option mentioned in this agreement?Extract the terms related to the Expansion Option provided in the lease document, including conditions, procedures, and any specific terms or requirements regarding Expansion Option",
        "What is the Termination Right's mentioned in this agreement?Extract the terms related to the Landlord's or Tenant’s right to terminate the lease, including the notice period, conditions, tenant obligations, and consequences of failure to vacate",
        "What is the Right of First Offer (ROFO) option mentioned in this agreement?Extract the terms related to the Right of First Offer (ROFO) option provided in the lease document, including conditions, procedures, and any specific terms or requirements",
        "What is the Default Clause mentioned in this agreement?Provide the details regarding Tenant's default conditions, including monetary and non-monetary defaults, and cure periods.",
        "Provide the lease section details regarding Tenant's obligations for late charges, interest on overdue payments, cure periods for defaults, and fees for returned checks, including conditions and rates applied.",
        "Provide the lease section details regarding Holdover Rent, including the conditions for determining holdover rent, any delay in applying increased rent during negotiations, and tenant obligations upon failing to surrender the premises.",
        "Provide details about the Contraction Option, including: whether the option is available, the period or timeframe during which the Tenant can exercise the option, the procedure and timeline for notifying the Landlord of the Tenant's intention to exercise the option, the amount or portion of the space that the Tenant intends to reduce, how the rent will be adjusted following the contraction, the effective date of the contraction, any associated costs or expenses, requirements related to the condition of the Premises after the contraction, the process for amending the lease agreement to reflect the contraction, and conditions under which the option may be waived or considered void. If any of these details are not available, please reply with 'NA'.",
        "Provide details about the Tenant's Insurance Clause, including: types of insurance required and the corresponding limits, requirements for the insurance policy form including the rating and qualifications of the insurance company, any additional insureds specified in the lease and any exceptions, and whether self-insurance is permitted and any related conditions. If any of these details are not available, please reply with 'NA'.",
        "Provide details about the Assignment Clause, including: notice and response periods required by the lease, whether any assignments are permitted without landlord approval and the conditions for consent, any rental adjustments that apply in the event of an assignment or sublet, landlord's options regarding consent, denial, termination, or recapture of premises, any assignment or processing fees required, and any profit share provided for subletting the premises. If any of these details are not available, please reply with 'NA'.",
        "Provide details about the Co-tenancy Clause, including the type of co-tenancy, co-tenancy condition, major tenants, any qualified replacement requirements, remedies for unsatisfied conditions, tenant's rights to terminate the lease if the co-tenancy condition remains unsatisfied, and any waivers or suspensions of co-tenancy rights. If any of these details are not available, please reply with 'NA'.",
        "Provide details about the Common Area Expenses, including how the Tenant's Proportionate Share is calculated, any excluded areas, inclusions and exclusions, administrative fees, payment structure, management fees, conditions for including capital repairs, reconciliation deadline, initial estimates, caps on increases, base year, gross-up provision, and tenant's audit rights. If any of these details are not available, please reply with 'NA'.",
        "Provide the Landlord's Notice Address details, including the full address, city, state, and zip code. If any of these details are not available, please reply with 'NA'.",
        "Provide details about the Guarantor, including the identity of the original guarantor, limitations of liability related to the guarantor (such as number of months and threshold amount), and any special terms and conditions related to the guarantee. If any of these details are not available, please reply with 'NA'.",
        "Provide the lease section details regarding the tenant's obligations upon lease termination, focusing on the surrender of the premises. Include the condition in which the premises must be returned any requirements for demolition or removal of improvements, and landlord's options",
        "Provide the lease section details regarding the Security Deposit, including the amount conditions for reduction, procedures for applying the deposit the timeframe for returning any unapplied balance.",
        "Provide the parking regulations details from the lease, including information on reserved and unreserved parking stalls, Parking Space rates, Parking Space grace period, Parking Space late fees and any special conditions imposed by the landlord",
        "Provide the utilities and services details from the lease, including HVAC service hours, any requirements for additional services, metered utilities, janitorial services, building access, and responsibilities for supplemental air conditioning units",
        "Extract the permitted use details from the lease document, including permitted use core and ancillary uses, as well as permitted categories and restrictions",
        "Extract the radius restriction details including Remedies from the lease document.",
        "Extract the Sales Kick Out termination rights, Sales_KirckOut conditions, and associated fees based on the lease document provided",
        "Extract the details related to signage rights as per the lease, including fascia signs, window coverings, seasonal promotions, channel letter signs, monument signs and pylon signage",
        "Extract the certification of lease terms details, including timelines for delivering certificates, the information required, and any reliance by third parties, from the lease document",
        "Extract the encumbrance and attornment details from the lease, including information on subordination to mortgages, requirements for non-disturbance agreements, and conditions for attornment",
        "Extract the Tenant Improvement Allowance (TIA) details from the lease, including conditions for reimbursement, specific exclusions, and repayment obligations upon early lease termination or assignment",
        "Extract the tenant relocation terms from the lease, including notice requirements, conditions for the new space, costs covered by the landlord, and tenant's options if the relocation space is not acceptable",
        "Extract the tenant’s maintenance and repair obligations, including details about what is included in the tenant's responsibilities and the process for reimbursing the landlord for repairs",
        "Extract the Landlord’s responsibilities for maintenance and repair, including details about the HVAC equipment, Common Areas, and structural components. Also, extract any restrictions on the Tenant’s ability to make repairs or seek rent abatement, and the Tenant's waiver of rights under specific laws.",
        "Extract the Tenant’s obligations and limitations regarding alterations to the Premises, including any conditions for making alterations, requirements for Landlord’s consent, supervision fees, and ownership of alterations",
        "Extract the Tenant's rights and responsibilities related to the installation, maintenance, and operation of a roof-mounted satellite dish antenna (the 'Dish'), including any conditions for installation, maintenance, relocation, and removal",
        "Extract the terms related to the Flex Furniture provided by the Landlord, including Flex Furniture delivery, Flex Furniture maintenance, Flex Furniture repair, Flex Furniture relocation, and Flex Furniture ownership conditions",
        "Extract the terms related to the Fitness Center provided in the lease document, including Fitness Center access, Fitness Center costs, and Fitness Center conditions",
        "Extract the terms related to the Conference Center provided in the lease document, including Conference Center access, Conference Center costs, and Conference Center conditions"
        ]


model_queries = ["What is the Trade Name or DBA or Do Business As Name in this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Trade Name or DBA' : ' '}. ",
                "What is the Lease Date or the Effective Date of this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Effective Date' : ' '}.Format the date as dd/mm/yyyy ",
                "Extract the details from the Basic Lease Details in this lease agreement.Give the answer in the following dictionary format and Do not add other text other than the answer.{'Tenant Name' : ' '}. ",
                "Extract the details from the Basic Lease Details in this lease agreement.Give the answer in the following dictionary format and Do not add other text other than the answer.{'Landlord Name' : ' '}. ",
                "What is the Premises Address mentioned this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Premises Address' : ' '}. ",
                "What is the Area of Premises mentioned this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Area of Premises' : ' '}. Give the answer with the metric.",
                "What is the Commencement Date  of this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Commencement Date' : ' '}.Format the date as dd/mm/yyyy ",
                "What is the Expiration terms of this agreement?.Calculate the Date from Commencement Date.Give the answer in the following dictionary format and Do not add other text other than the answer.{'Expiration Terms' : ' ' ,'Expiration Date' : ' '}.Format the date as dd/mm/yyyy ",
                "What is the Tenant Notice Address mentioned this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Tenant Notice Address' : ' '}. ",
                "What is the Tenant Notice Copy To Address mentioned this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Tenant Notice Copy To Address' : ' '}. ",
                "What is the Billing Address mentioned this agreement?Give the answer in the following dictionary format and Do not add other text other than the answer.{'Billing Address' : ' '}. ",
                "Extract the Base Rent terms provided in the lease document including all the columns and rows.Give the answer in the following dictionary format and Do not add other text other than the answer.{{'Column Name':'Rows'}}.Format the date as dd/mm/yyyy.Format the amount as '$[Amount]'. ",
                "Extract the Additional Rent terms which are other than Base Rent from the lease document including all the columns and rows.Give the answer in the following dictionary format and Do not add other text other than the answer.{{'Column Name':'Rows'}}.Format the date as dd/mm/yyyy.Format the amount as '$[Amount]'. ",
                "Extract the terms related to the Renewal Option provided in the lease document, including notice period, term, rental rate, annual rent increases, and conditions for exercising the option.Give the answer in the following dictionary format and Do not add other text other than the answer.{'NOTICE PERIOD':' ' ,'TERM':' ', 'BREAKPOINT':' ' ,'RENTAL RATE':' ', 'ANNUAL RENT INCREASES DURING OPTION TERM':' ' ,'SALES TEST':' ', 'CONDITIONS FOR EXERCISING THE OPTION':' ' }. ",
                "Extract the terms related to the Expansion Option provided in the lease document, including conditions, procedures, and any specific terms or requirements.Give the answer in the following dictionary format and Do not add other text other than the answer.{'EXPANSION OPTION':' ' ,'CONDITIONS FOR EXERCISE':' ','EXERCISE PROCEDURE':' ' ,'TERMS OF EXPANSION':' ','SPACE ALLOCATION':' ' ,'COSTS AND EXPENSES':' ','RENT ADJUSTMENT':' '}. ",
                "Extract and summarize the terms related to the Landlord's or Tenant’s right to terminate the lease, including the notice period, conditions, tenant obligations, and consequences of failure to vacate.Give the answer in the following dictionary format and Do not add other text other than the answer.{'NOTICE PERIOD':' ' ,'CONDITIONS FOR TERMINATION':' ','TENANT OBLIGATIONS':' ' ,'CONSEQUENCES OF FAILURE TO VACATE':' ','COMPENSATION TO TENANT':' ' ,'TERMINATION FEE':' ','ONGOING LIABILITY':' '}. ",
                "Extract the terms related to the Right of First Offer (ROFO) option provided in the lease document, including conditions, procedures, and any specific terms or requirements.Give the answer in the following dictionary format and Do not add other text other than the answer.{'RIGHT OF FIRST OFFER (ROFO)':' Yes/No ' ,'CONDITIONS FOR EXERCISE':' ','EXERCISE PROCEDURE':' ' ,'SPACE DESCRIPTION':' ','OFFER TERMS':' ' ,'RENT AND LEASE TERMS':' ','WAIVER OF ROFO':' ','OTHER CONDITIONS':' ' }. ",
                "Provide the details regarding Tenant's default conditions, including monetary and non-monetary defaults, and cure periods and calculate the days for each.Give the answer in the following dictionary format and Do not add other text other than the answer.{'MONETARY DEFAULT':' ' ,'NON-MONETARY DEFAULT':' '}. ",
                "Provide the lease section details regarding Tenant's obligations for late charges, interest on overdue payments, cure periods for defaults, and fees for returned checks, including conditions and rates applied and calculate the days and amount respectively.Give the answer in the following dictionary format and Do not add other text other than the answer.{'LATE CHARGES':' ','INTEREST ON OVERDUE PAYMENTS':' ','CURE PERIODS FOR DEFAULTS':' ','RETURNED CHECK FEE':' '}. ",
                "Provide the lease section details regarding Holdover Rent, including the conditions for determining holdover rent, any delay in applying increased rent during negotiations, and tenant obligations upon failing to surrender the premises.Give the answer in the following dictionary format and Do not add other text other than the answer.{'HOLDOVER RENT':' ','DELAYED RENT INCREASE':' '}. "
                "Provide the details related to the Contraction Option in the following dictionary format. Include information about whether the option is available, the period or timeframe during which the Tenant can exercise the option, the procedure and timeline for notifying the Landlord, the amount or portion of the space that Tenant intends to reduce, how the rent will be adjusted, the effective date of the contraction, any associated costs or expenses, the condition of the Premises following the contraction, the process for amending the lease, and conditions under which the option may be waived.Do not add other text other than the answer. Format the answer as follows: {'CONTRACTION OPTION':' ', 'CONTRACTION PERIOD':' ', 'NOTICE REQUIREMENTS':' ', 'REDUCED SPACE':' ', 'RENT ADJUSTMENT':' ', 'CONTRACTION EFFECTIVE DATE':' ', 'COSTS AND EXPENSES':' ', 'CONDITION OF PREMISES':' ', 'AMENDMENT TO LEASE':' ', 'WAIVER OF OPTION':' '}. ",
                "Provide the details related to the Tenants Insurance Clause in the following dictionary format. Include information about types of insurance required and the corresponding limits, requirements for the insurance policy form, any additional insureds specified in the lease and exceptions, and whether self-insurance is permitted and any related conditions.Do not add other text other than the answer. Format the answer as follows: {'TYPES_LIMITS':' ', 'POLICY_FORM':' ', 'ADDITIONAL_INSUREDS':' ', 'SELF_INSURANCE':' '}. ",
                "Provide the details related to the Assignment Clause in the following dictionary format. Include information about notice and response periods, landlord consent requirements, rental adjustments, landlord's options, assignment fees, and profit share. Give the answer in the following dictionary format and do not add other text other than the answer. Format the answer as follows: {'NOTICE_LL_RESPONSE_PERIODS':' ', 'Landlord_Consent_Required':' ', 'RENTAL_ADJUSTMENT':' ', 'LANDLORDS_OPTIONS':' ', 'ASSIGNMENT_FEE':' ', 'PROFIT_SHARE':' '}. ",
                "Provide the details related to the Co-tenancy Clause in the following dictionary format. Include information about the type of co-tenancy, co-tenancy condition, major tenants, any qualified replacement requirements, remedies for unsatisfied conditions, termination rights, and any waivers or suspensions of co-tenancy rights. Give the answer in the following dictionary format and do not add other text other than the answer. Format the answer as follows: {'CO_TENANCY_CONDITION':' ', 'REMEDIES_FOR_UNSATISFIED_CONDITION':' ', 'TERMINATION_RIGHTS':' ', 'CO_TENANCY_SUSPENSION':' '}. ",
                "Provide the details related to Common Area Expenses in the following dictionary format. Include information about the prorata share method, excluded areas, inclusions, exclusions, administrative fee, payment structure, management fee, capital repairs, reconciliation deadline, estimates, caps on increases, base year, gross-up provision, and audit rights. Give the answer in the following dictionary format and do not add other text other than the answer. Format the answer as follows: {'Prorata_Share_Method':' ', 'Excluded_Area':' ', 'Inclusions':' ', 'Exclusions':' ', 'Administrative_Fee':' ', 'Payments':' ', 'Management_Fee':' ', 'Capital_Repairs':' ', 'Reconciliation_Deadline':' ', 'Estimates':' ', 'CAP':' ', 'Base_Year':' ', 'Gross_Up':' ', 'Audit':' '}. ",
                "Provide the details related to the Landlord Notice Address in the following dictionary format. Include the full address, city, state, and zip code. Give the answer in the following dictionary format and do not add other text other than the answer. Format the answer as follows: {'full_address':' ', 'city':' ', 'state':' ', 'zip_code':' '}. ",
                "Provide the details related to the Guarantor in the following dictionary format. Include the identity of the original guarantor, limitations of liability (number of months, threshold amount), and any special terms and conditions related to the guarantee. Format the answer as follows: {'GUARANTOR':' ', 'LIMITATIONS_OF_LIABILITY':' ', 'SPECIAL_TERMS_CONDITIONS':' '}."
                "Provide the lease section details regarding the tenant's obligations upon lease termination, focusing on the surrender of the premises. Include the condition in which the premises must be returned any requirements for demolition or removal of improvements, and landlord's options. Give the answer in the following dictionary format and Do not add other text other than the answer.{'SURRENDER OF PREMISES CONDITION':' ','DEMOLITION AND REMOVAL':' ', 'LANDLORD'S OPTIONS':' '}.",
                "Provide the lease section details regarding the Security Deposit, including the amount conditions for reduction, procedures for applying the deposit the timeframe for returning any unapplied balance.Give the answer in the following dictionary format and Do not add other text other than the answer.{'SECURITY DEPOSIT AMOUNT': ' '}, {'DEPOSIT TYPE': ' '}, {'APPLICATION OF SECURITY DEPOSIT': ' '}, {'Interest on Deposit': ' '}, {'RETURN OF SECURITY DEPOSIT': ' '}, {'CONDITIONS FOR REDUCTION': ' '}.",
                "Provide the parking regulations details from the lease, including information on reserved and unreserved parking stalls, Parking Space rates, Parking Space grace period, Parking Space late fees and any special conditions imposed by the landlord. Give the answer in the following dictionary format and Do not add other text other than the answer. {'RESERVED PARKING STALLS AND RATE': ' '}, {'UNRESERVED PARKING STALLS AND RATE': ' '}, {'GRACE PERIOD AND LATE FEE': ' '}, {'SPECIAL CONDITIONS': ' '}",
                "Provide the utilities and services details from the lease, including HVAC service hours, any requirements for additional services, metered utilities, janitorial services, building access, and responsibilities for supplemental air conditioning units. Give the answer in the following dictionary format and Do not add other text other than the answer. {'HVAC_SERVICE_HOURS': ' '}, {'ADDITIONAL_SERVICES': ' '}, {'METERED_UTILITIES': ' '}, {'JANITORIAL_SERVICES': ' '}, {'SUPPLEMENTAL_AIR_CONDITIONING': ' '}",
                "Extract the permitted use details from the lease document, including permitted use core and ancillary uses, as well as permitted categories and restrictions. Give the answer in the following dictionary format and Do not add other text other than the answer. {'TENANTS CORE USE': ' '}, {'TENANTS ANCILLARY USE': ' '}, {'RESTRICTIONS AND CONDITIONS': ' '}",
                "Extract the radius restriction details including Remedies from the lease document. Give the answer in the following dictionary format and Do not add other text other than the answer. {'Radius Distance': ' '}, {'Restricted Locations': ' '}, {'Exceptions': ' '}, {'REMEDIES FOR UNSATISFIED CONDITION': ' '}, {'TERMINATION RIGHTS': ' '}",
                "Extract the Sales Kick Out termination rights, Sales_KirckOut conditions, and associated fees based on the lease document provided. Give the answer in the following dictionary format and Do not add other text other than the answer. {'NOTICE PERIOD': ' '}, {'CRITERIA': ' '}, {'COMPENSATION TO TENANT BY LANDLORD': ' '}, {'COMPENSATION TO LANDLORD BY TENANT': ' '}, {'GO DARK OR TERMINATE': ' '}, {'TERMINATION FEE PAID BY TENANT': ' '}, {'Sales_KirckOut NOTES': ' '}",
                "Extract the details related to signage rights as per the lease, including fascia signs, window coverings, seasonal promotions, channel letter signs, monument signs and pylon signage. Give the answer in the following dictionary format and Do not add other text other than the answer. {'FASCIA SIGNAGE PROGRAM': ' '}, {'LOBBY AND SUITE SIGN': ' '}, {'WINDOW COVERING PROGRAM': ' '}, {'SEASONAL PROMOTION BANNERS': ' '}, {'CHANNEL LETTER SIGNS': ' '}, {'MONUMENT SIGNAGE RIGHTS': ' '}, {'PYLON SIGNAGE RIGHTS': ' '}",
                "Extract the certification of lease terms details, including timelines for delivering certificates, the information required, and any reliance by third parties, from the lease document. Give the answer in the following dictionary format and Do not add other text other than the answer.{'CERTIFICATION TIMELINE': ' '}, {'CERTIFICATION CONTENT': ' '}",
                "Extract the encumbrance and attornment details from the lease, including information on subordination to mortgages, requirements for non-disturbance agreements, and conditions for attornment. Give the answer in the following dictionary format and Do not add other text other than the answer. {'SUBORDINATION TO MORTGAGE': ' '}, {'NON DISTURBANCE AGREEMENT': ' '}, {'ATTORNMENT': ' '}",
                "Extract the Tenant Improvement Allowance (TIA) details from the lease, including conditions for reimbursement, specific exclusions, and repayment obligations upon early lease termination or assignment. Give the answer in the following dictionary format and Do not add other text other than the answer. {'TENANT IMPROVEMENT ALLOWANCE': ' '}, {'REPAYMENT OBLIGATIONS': ' '}",
                "Extract the tenant relocation terms from the lease, including notice requirements, conditions for the new space, costs covered by the landlord, and tenant's options if the relocation space is not acceptable. Give the answer in the following dictionary format and Do not add other text other than the answer. {'RELOCATION RIGHTS': ' '}, {'REIMBURSEMENT OF COSTS': ' '}, {'TENANTS OPTIONS': ' '}",
                "Extract the tenant’s maintenance and repair obligations, including details about what is included in the tenant's responsibilities and the process for reimbursing the landlord for repairs. Give the answer in the following dictionary format and Do not add other text other than the answer. {'TENANTS MAINTENANCE OBLIGATIONS': ' '}, {'REIMBURSEMENT OF REPAIR COSTS': ' '}",
                "Extract the Landlord’s responsibilities for maintenance and repair, including details about the HVAC equipment, Common Areas, and structural components. Also, extract any restrictions on the Tenant’s ability to make repairs or seek rent abatement, and the Tenant's waiver of rights under specific laws. Give the answer in the following dictionary format and Do not add other text other than the answer. {'LANDLORDS MAINTENANCE AND REPAIR RESPONSIBILITIES': ' '}, {'TENANTS REPAIR RESTRICTIONS': ' '}",
                "Extract the Tenant’s obligations and limitations regarding alterations to the Premises, including any conditions for making alterations, requirements for Landlord’s consent, supervision fees, and ownership of alterations. Give the answer in the following dictionary format and Do not add other text other than the answer. {'COSMETIC ALTERATIONS': ' '}, {'ALTERATIONS REQUIRING LANDLORDS CONSENT': ' '}, {'SUPERVISION FEE': ' '}, {'OWNERSHIP AND REMOVAL OF ALTERATIONS': ' '}",
                "Extract the Tenant's rights and responsibilities related to the installation, maintenance, and operation of a roof-mounted satellite dish antenna (the 'Dish'), including any conditions for installation, maintenance, relocation, and removal Give the answer in the following dictionary format and Do not add other text other than the answer. {'INSTALLATION AND MAINTENANCE': ' '}, {'Satellite Dish RELOCATION': ' '}, {'REPAIRS AND REPLACEMENTS': ' '}, {'PROPERTY AND LIEN ISSUES': ' '}",
                "Extract the terms related to the Flex Furniture provided by the Landlord, including Flex Furniture delivery, Flex Furniture maintenance, Flex Furniture repair, Flex Furniture relocation, and Flex Furniture ownership conditions. Give the answer in the following dictionary format and Do not add other text other than the answer. {'DELIVERY AND INSTALLATION': ' '}, {'USE AND MAINTENANCE': ' '}, {'OWNERSHIP AND EXTENSION TERMS': ' '}",
                "Extract the terms related to the Fitness Center provided in the lease document, including Fitness Center access, Fitness Center costs, and Fitness Center conditions. Give the answer in the following dictionary format and Do not add other text other than the answer. {'FITNESS CENTER ACCESS AND USE': ' '}, {'FITNESS CENTER COSTS AND EXPENSES': ' '}, {'FITNESS CENTER MODIFICATION AND LIABILITY': ' '}, {'FITNESS CENTER TRANSFER AND ASSIGNMENT': ' '}",
                "Extract the terms related to the Conference Center provided in the lease document, including Conference Center access, Conference Center costs, and Conference Center conditions. Give the answer in the following dictionary format and Do not add other text other than the answer. {'CONFERENCE CENTER ACCESS AND USE': ' '}, {'CONFERENCE CENTER COSTS AND EXPENSES': ' '}, {'CONFERENCE CENTER MODIFICATION AND LIABILITY': ' '}, {'CONFERENCE CENTER TRANSFER AND ASSIGNMENT': ' '}"
                ]


model_formats = [
                "{'Trade Name or DBA' : ' '},{'Sec' : [' ']})",
                "{'Effective Date' : ' '},{'Sec' : [' ']}",
                "{'Tenant Name' : ' '},{'Sec' : [' ']}",
                "{'Landlord Name' : ' '},{'Sec' : [' ']}",
                "{'Premises Address' : {'full_address':' ', 'city':' ', 'state':' ', 'zip_code':' '}},{'Sec' : [' ']}", 
                "{'Area of Premises' : ' '},{'Sec' : [' ']}",
                "{'Commencement Date' : ' '},{'Sec' : [' ']}",
                "{'Expiration Date' : ' '},{'Sec' : [' ']}",
                "{'Tenant Notice Address' : {'full_address':' ', 'city':' ', 'state':' ', 'zip_code':' '}},{'Sec' : [' ']}",
                "{'Tenant Notice Copy To Address' : {'full_address':' ', 'city':' ', 'state':' ', 'zip_code':' '}},{'Sec' : [' ']}",
                "{'Billing Address' : ' '},{'Sec' : [' ']}",
                "{'Base Rent' : {'Column Name':['Rows']}},{'Sec' : [' ']}",
                "{'Additional Rent' : {'Column Name':['Rows']}},{'Sec' : [' ']}",
                "{'Renewal Option' : {'NOTICE PERIOD':' ' ,'TERM':' ', 'BREAKPOINT':' ' ,'RENTAL RATE':' ', 'ANNUAL RENT INCREASES DURING OPTION TERM':' ' ,'SALES TEST':' ', 'CONDITIONS FOR EXERCISING THE OPTION':' ' }}",
                "{'Expansion_Option' : {'EXPANSION OPTION':' ' ,'CONDITIONS FOR EXERCISE':' ','EXERCISE PROCEDURE':' ' ,'TERMS OF EXPANSION':' ','SPACE ALLOCATION':' ' ,'COSTS AND EXPENSES':' ','RENT ADJUSTMENT':' '}}",
                "{'Termination_Right' : {'NOTICE PERIOD':' ' ,'CONDITIONS FOR TERMINATION':' ','TENANT OBLIGATIONS':' ' ,'CONSEQUENCES OF FAILURE TO VACATE':' ','COMPENSATION TO TENANT':' ' ,'TERMINATION FEE':' ','ONGOING LIABILITY':' '}}",
                "{'RIGHT_OF_FIRST_OFFER' : {'RIGHT OF FIRST OFFER (ROFO)':' Yes/No ' ,'CONDITIONS FOR EXERCISE':' ','EXERCISE PROCEDURE':' ' ,'SPACE DESCRIPTION':' ','OFFER TERMS':' ' ,'RENT AND LEASE TERMS':' ','WAIVER OF ROFO':' ','OTHER CONDITIONS':' ' }}",
                "{'Default_Clause' : {'MONETARY DEFAULT':' ' ,'NON-MONETARY DEFAULT':' '}}",
                "{'Late_Charges' : {'LATE CHARGES':' ','INTEREST ON OVERDUE PAYMENTS':' ','CURE PERIODS FOR DEFAULTS':' ','RETURNED CHECK FEE':' '}}",
                "{'Holdover_Rent' : {'HOLDOVER RENT':' ','DELAYED RENT INCREASE':' '}}",
                "{'Contraction_Option' : {'CONTRACTION OPTION': ' ', 'CONTRACTION PERIOD': ' ', 'NOTICE REQUIREMENTS': ' ', 'REDUCED SPACE': ' ', 'RENT ADJUSTMENT': ' ', 'CONTRACTION EFFECTIVE DATE': ' ', 'COSTS AND EXPENSES': ' ', 'CONDITION OF PREMISES': ' ', 'AMENDMENT TO LEASE': ' ', 'WAIVER OF OPTION': ' '}}",
                "{'Tenants_Insurance_Clause' : {'TYPES_LIMITS': ' ', 'POLICY_FORM': ' ', 'ADDITIONAL_INSUREDS': ' ', 'SELF_INSURANCE': ' '}}",
                "{'Assignment_Clause' : {'NOTICE_LL_RESPONSE_PERIODS': ' ', 'Landlord_Consent_Required': ' ', 'RENTAL_ADJUSTMENT': ' ', 'LANDLORDS_OPTIONS': ' ', 'ASSIGNMENT_FEE': ' ', 'PROFIT_SHARE': ' '}}",
                "{'Co_tenancy_Clause' : {'CO_TENANCY_CONDITION':' ', 'REMEDIES_FOR_UNSATISFIED_CONDITION':' ', 'TERMINATION_RIGHTS':' ', 'CO_TENANCY_SUSPENSION':' '}}",
                "{'Common_Area_Expenses' : {'Prorata_Share_Method':' ', 'Excluded_Area':' ', 'Inclusions':' ', 'Exclusions':' ', 'Administrative_Fee':' ', 'Payments':' ', 'Management_Fee':' ', 'Capital_Repairs':' ', 'Reconciliation_Deadline':' ', 'Estimates':' ', 'CAP':' ', 'Base_Year':' ', 'Gross_Up':' ', 'Audit':' '}}",
                "{'Landlord_Notice_Address' : {'full_address':' ', 'city':' ', 'state':' ', 'zip_code':' '}}",
                "{'Guarantor' : {'GUARANTOR':' ', 'LIMITATIONS_OF_LIABILITY':' ', 'SPECIAL_TERMS_CONDITIONS':' '}}",
                "{'Surrender' : {'SURRENDER OF PREMISES CONDITION':' ','DEMOLITION AND REMOVAL':' ', 'LANDLORD'S OPTIONS':' '}}",
                "{'Security_Deposit' : {'SECURITY DEPOSIT AMOUNT': ' ','DEPOSIT TYPE': ' ', 'APPLICATION OF SECURITY DEPOSIT': ' ', 'Interest on Deposit': ' ', 'RETURN OF SECURITY DEPOSIT': ' ', 'CONDITIONS FOR REDUCTION': ' '}}",
                "{'Parking_Space' : {'RESERVED PARKING STALLS AND RATE': ' ','UNRESERVED PARKING STALLS AND RATE': ' ','GRACE PERIOD AND LATE FEE': ' ','SPECIAL CONDITIONS': ' '}}",
                "{'Utilities' : {'HVAC SERVICE HOURS': ' ','ADDITIONAL SERVICES': ' ', 'METERED UTILITIES': ' ', 'JANITORIAL SERVICES': ' ', 'SUPPLEMENTAL AIR CONDITIONING': ' '}}",
                "{'Permitted_Use' : {'TENANTS CORE USE': ' ', 'TENANTS ANCILLARY USE': ' ', 'RESTRICTIONS AND CONDITIONS': ' '}}",
                "{'Radius_Restriction' : {'Radius Distance': ' ', 'Restricted Locations': ' ', 'Exceptions': ' ', 'REMEDIES FOR UNSATISFIED CONDITION': ' ', 'TERMINATION RIGHTS': ' '}}",
                "{'Sales_KirckOut' : {'NOTICE PERIOD': ' ', 'CRITERIA': ' ', 'COMPENSATION TO TENANT BY LANDLORD': ' ', 'COMPENSATION TO LANDLORD BY TENANT': ' ', 'GO DARK OR TERMINATE': ' ', 'TERMINATION FEE PAID BY TENANT': ' ', 'Sales_KirckOut NOTES': ' '}}",
                "{'Signage_Clause' : {'FASCIA SIGNAGE PROGRAM': ' ', 'LOBBY AND SUITE SIGN': ' ', 'WINDOW COVERING PROGRAM': ' ', 'SEASONAL PROMOTION BANNERS': ' ', 'CHANNEL LETTER SIGNS': ' ', 'MONUMENT SIGNAGE RIGHTS': ' ', 'PYLON SIGNAGE RIGHTS': ' '}}",
                "{'Estoppel_Certificate' : {'CERTIFICATION TIMELINE': ' ', 'CERTIFICATION CONTENT': ' '}}",
                "{'Subordination_SNDA' : {'SUBORDINATION TO MORTGAGE': ' ', 'NON DISTURBANCE AGREEMENT': ' ', 'ATTORNMENT': ' '}}",
                "{'Tenant_Improvement_Allowance' : {'TENANT IMPROVEMENT ALLOWANCE': ' ', 'REPAYMENT OBLIGATIONS': ' '}}",
                "{'Relocation' :{'RELOCATION RIGHTS': ' ', 'REIMBURSEMENT OF COSTS': ' ', 'TENANTS OPTIONS': ' '}}",
                "{'Tenants_Maintenance' : {'TENANTS MAINTENANCE OBLIGATIONS': ' ', 'REIMBURSEMENT OF REPAIR COSTS': ' '}}",
                "{'Landlord_Maintenance' : {'LANDLORDS MAINTENANCE AND REPAIR RESPONSIBILITIES': ' ', 'TENANTS REPAIR RESTRICTIONS': ' '}}",
                "{'Alterations' : {'COSMETIC ALTERATIONS': ' ', 'ALTERATIONS REQUIRING LANDLORDS CONSENT': ' ', 'SUPERVISION FEE': ' ', 'OWNERSHIP AND REMOVAL OF ALTERATIONS': ' '}}",
                "{'Satellite_Dish' : {'INSTALLATION AND MAINTENANCE': ' ', 'Satellite Dish RELOCATION': ' ', 'REPAIRS AND REPLACEMENTS': ' ', 'PROPERTY AND LIEN ISSUES': ' '}}",
                "{'Flex_Furniture' : {'DELIVERY AND INSTALLATION': ' ', 'USE AND MAINTENANCE': ' ', 'OWNERSHIP AND EXTENSION TERMS': ' '}}",
                "{'Fitness_Center' : {'FITNESS CENTER ACCESS AND USE': ' ', 'FITNESS CENTER COSTS AND EXPENSES': ' ', 'FITNESS CENTER MODIFICATION AND LIABILITY': ' ', 'FITNESS CENTER TRANSFER AND ASSIGNMENT': ' '}}",
                "{'Conference_Center' : {'CONFERENCE CENTER ACCESS AND USE': ' ', 'CONFERENCE CENTER COSTS AND EXPENSES': ' ', 'CONFERENCE CENTER MODIFICATION AND LIABILITY': ' ', 'CONFERENCE CENTER TRANSFER AND ASSIGNMENT': ' '}}"
                ]   

